language: php

php:
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
